version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: ./celery-queue/Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: .
      dockerfile: ./celery-queue/Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'